






































































100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 257/257 [02:23<00:00,  1.80it/s]

















100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 257/257 [00:36<00:00,  7.13it/s]
Traceback (most recent call last):
  File "/home/barry/Desktop/uni/dbl2/JBG040-Group19/final/main.py", line 204, in <module>
    main()
  File "/home/barry/Desktop/uni/dbl2/JBG040-Group19/final/main.py", line 198, in main
    best_model = trainModel(args.model, device, args.drop_rate, args.optimizer, args.learning_rate, args.scheduler, args.criterion, weights, args.epochs, train_loader, test_loader, args.early_stop_thresh)
  File "/home/barry/Desktop/uni/dbl2/JBG040-Group19/final/main.py", line 174, in trainModel
    best_model = train_loop(epochs, train_loader, device, optimizer, model, criterion, test_loader, early_stop_thresh, fast=False)
  File "/home/barry/Desktop/uni/dbl2/JBG040-Group19/final/train_test.py", line 83, in train_loop
    checkpoint(model, epoch, 'best')
  File "/home/barry/Desktop/uni/dbl2/JBG040-Group19/final/train_test.py", line 14, in checkpoint
    torch.save(model.state_dict(), f"models/{r}")
  File "/home/barry/anaconda3/envs/dbl2/lib/python3.10/site-packages/torch/serialization.py", line 422, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/home/barry/anaconda3/envs/dbl2/lib/python3.10/site-packages/torch/serialization.py", line 309, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/home/barry/anaconda3/envs/dbl2/lib/python3.10/site-packages/torch/serialization.py", line 287, in __init__
    super(_open_zipfile_writer_file, self).__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory models does not exist.